name: Release

on:
  push:
    branches:
      - master

jobs:
  get:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Determine Version
        uses: trs/inc-semver-action@master
        id: semver_module1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          directory: ./modules/module_1
          prefix: module_1@v
      - name: Create Release
        if: ${{ steps.semver_module1.outputs.nextTag }} != ''
        id: release_module1
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver_module1.outputs.nextTag }}
          release_name: v${{ steps.semver_module1.outputs.nextVersion }}
          body: ${{ steps.semver_module1.outputs.changelog }}
      - name: Determine Version
        uses: trs/inc-semver-action@master
        id: semver_module2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          directory: ./modules/module_2
          prefix: module_2@v
      - name: Create Release
        if: ${{ steps.semver_module2.outputs.nextTag }} != ''
        id: release_module2
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver_module2.outputs.nextTag }}
          release_name: v${{ steps.semver_module2.outputs.nextVersion }}
          body: ${{ steps.semver_module2.outputs.changelog }}
